---
- hosts: all
  gather_facts: no
  remote_user: deploy
  vars_files:
    - ../secrets.yml
  tasks:
    - name: Install pip
      apt:
        name:
          - python-pip
      become: yes
    - name: Install docker python package
      pip:
        name:
          - docker
      become: yes
    - name: Copy nginx build files
      copy:
        src: build-nginx
        dest: /home/
    - name: Stop bedford-nginx container
      docker_container:
        name: bedford-nginx
        state: absent
      become: yes
    - name: Build bedford-nginx image
      docker_image:
        name: bedford-nginx
        path: build-nginx
        force: yes
      become: yes
    - name: Run bedford-nginx container
      docker_container:
        name: bedford-nginx
        image: bedford-nginx
        published_ports:
          - 80:80
        volumes:
          - /var/sftp/bedfordvamuseum:/usr/share/nginx/html:ro
        log_options:
          max-size: 5m
          max-file: 10
      become: yes
