AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Metrics/LineLength:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/AbcSize:
  Enabled: false