version: '3'
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - ${VOLUME_MOUNTS_DIR}/db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: always
  rails:
    image: bedford_rails
    volumes:
      - ${VOLUME_MOUNTS_DIR}/rails/public/system:/rails/public/system
      - ${VOLUME_MOUNTS_DIR}/rails_secrets.yml:/rails/config/secrets.yml:ro
    depends_on:
      - db
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: always
    environment:
      - ENVIRONMENT
  nginx:
    image: nginx:alpine
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${VOLUME_MOUNTS_DIR}/nginx/default.template:/etc/nginx/conf.d/default.template:ro
      - ${VOLUME_MOUNTS_DIR}/nginx/htpasswd:/etc/apache2/.htpasswd:ro
      - ${VOLUME_MOUNTS_DIR}/static:/usr/share/nginx/html:ro
    depends_on:
      - rails
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: always
    environment:
      - PORT
      - SERVER_NAME
    command: "/bin/sh -c \"apk add --no-cache --virtual templating gettext \
      && envsubst '$$SERVER_NAME $$PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf \
      && apk del templating \
      && exec nginx -g 'daemon off;'\""
