---
- become: yes
  gather_facts: no
  hosts: all
  remote_user: deploy
  vars_files:
    - ../secrets.yml
  tasks:
    - name: Transfer static site content
      command: rclone sync spaces:bedfordvamuseum/static /var/sftp/bedfordvamuseum
    - name: Set owner and group for the static site content
      file:
        path: /var/sftp/bedfordvamuseum
        state: directory
        recurse: yes
        owner: sftp
        group: sftp
    - name: Ensure directories are 0755
      command: find /var/sftp/bedfordvamuseum -type d ! -perm 0755 -exec chmod 0755 {} \;
    - name: Ensure files are 0644
      command: find /var/sftp/bedfordvamuseum -type f ! -perm 0644 -exec chmod 0644 {} \;
    - name: Create cron job to keep static content synced with spaces bucket
      cron:
        name: spaces sync
        special_time: daily
        job: rclone sync /var/sftp/bedfordvamuseum spaces:bedfordvamuseum/static
      when: prod
