default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  template: template0

development:
  <<: *default
  database: bedford_development

test:
  <<: *default
  database: bedford_test

production:
  <<: *default
  database: bedford_production
