---
- become: true
  gather_facts: false
  hosts: all
  remote_user: "{{ admin_user_name }}"
  vars_files:
    - ../common_secrets.yml
    - ../common_vars.yml
  tasks:
    - name: Create data directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ mount_point }}/db"
        - "{{ mount_point }}/rails/public/system"
        - "{{ mount_point }}/letsencrypt"
    - name: Copy files
      copy:
        src: "{{ lookup('env','DEPLOY_FILES_DIR') }}/"
        dest: "{{ admin_home_dir }}/"
        force: true
    - name: Load rails image
      docker_image:
        load_path: "{{ admin_home_dir }}/rails/image.tar"
        name: rails
        source: load
        force_source: true
    - name: Build custom nginx image
      docker_image:
        build:
          path: "{{ admin_home_dir }}/nginx"
          pull: false
        name: nginx-certbot
        source: build
        force_source: true
    - name: Initialize certbot
      docker_container:
        cleanup: true
        command: certbot-init.sh
        detach: false
        env:
          ADMIN_EMAIL: "{{ admin_email }}"
          DOMAIN_NAME: "{{ domain_name }}"
        image: nginx-certbot
        name: certbot-init
        published_ports:
          - 80:80/tcp
          - 443:443/tcp
        volumes:
          - "{{ mount_point }}/letsencrypt:/etc/letsencrypt"
