---
- hosts: all
  remote_user: root
  tasks:
    - name: Add apt keys
      apt_key:
        url: "{{ item }}"
      loop:
        - https://download.docker.com/linux/debian/gpg
        - https://repos.sonar.digitalocean.com/sonar-agent.asc
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
    - name: Add apt repos
      apt_repository:
        repo: "{{ item }}"
      loop:
        - deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        - deb https://repos.sonar.digitalocean.com/apt main main
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        autoclean: yes
        autoremove: yes
        upgrade: yes
    - name: Install packages with apt
      apt:
        name:
          - debconf
          - debconf-utils
          - do-agent
          - docker-ce
          - fail2ban
          - logwatch
          - parted
          - postfix
          - python-pip
          - ufw
          - unattended-upgrades
          - unzip
    - name: Install packages with pip
      pip:
        name:
          - docker
          - docker-compose
