---
- hosts: all
  remote_user: root
  vars_files:
    - resources/secrets.yml
  vars:
    tcp_ports:
      - 22
      - 80
  tasks:
    - name: Configure APT update intervals
      copy:
        src: resources/apt-auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
    - name: Configure firewall
      ufw:
        state: enabled
        policy: deny
    - name: Open specific TCP ports
      ufw:
        rule: allow
        proto: tcp
        to_port: "{{ item }}"
      loop: "{{ tcp_ports }}"
    - name: Set up Postfix to relay mail
      debconf:
        name: postfix
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - question: postfix/mailname
          value: "{{ ansible_fqdn }}"
          vtype: string
        - question: postfix/main_mailer_type
          value: Internet Site
          vtype: string
    - name: Avoid leaking version info
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: ^smtpd_banner
        line: smtpd_banner = $myhostname ESMTP
        create: yes
    - name: Configure logwatch cron job with correct email address
      lineinfile:
        path: /etc/cron.daily/00logwatch
        regexp: ^/usr/sbin/logwatch
        line: /usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high
        create: yes
