---
- hosts: all
  remote_user: root
  vars_files:
    - resources/vars.yml
  tasks:
    - name: Partition the volume if needed
      parted:
        device: "{{ volume }}"
        label: gpt
        number: 1
        state: present
    - name: Create EXT filesystem if needed
      filesystem:
        fstype: ext4
        dev: "{{ partition }}"
    - name: Mount persistent volume
      mount:
        fstype: ext4
        opts: defaults,discard,noatime,nofail
        path: "{{ mount_point }}"
        src: "{{ partition }}"
        state: mounted
