---
version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: unless-stopped
  rails:
    image: rails
    environment:
      - RAILS_ENV=production
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD
    volumes:
      - ${DATA_DIR}/rails/public/system:/app/public/system
      - ${RAILS_CONFIG_DIR}/rails_secrets.yml:/app/config/secrets.yml:ro
    depends_on:
      - db
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: unless-stopped
  nginx:
    image: nginx-certbot
    environment:
      - DOMAIN_NAME
    command: "/bin/sh -c \
      \"envsubst '$$DOMAIN_NAME' \
      < /default.conf.template \
      > /etc/nginx/conf.d/default.conf \
      && exec nginx -g 'daemon off;'\""
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${DATA_DIR}/sftp/bedfordvamuseum:/usr/share/nginx/html:ro
      - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
    depends_on:
      - rails
    logging:
      options:
        max-size: 5m
        max-file: '10'
    restart: unless-stopped
