source 'https://rubygems.org'

gem 'paperclip', '~> 6.0'
gem 'bootstrap', '~> 4.1'
gem 'coffee-rails', '~> 4.2'
gem 'devise', '~> 4.4'
gem 'devise_account_expireable', '~> 0.0'
gem 'devise_invitable', '~> 1.7'
gem 'friendly_id', '~> 5.2'
gem 'jbuilder', '~> 2.7'
gem 'jquery-rails', '~> 4.3'
gem 'mailgun-ruby', '~> 1.1'
gem 'pg', '~> 0.21'
gem 'rails', '~> 4.2'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4', group: :doc
gem 'simple_form', '~> 3.5'
gem 'turbolinks', '~> 5.1'
gem 'uglifier', '~> 4.1'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'faker', '~> 1.8'
  gem 'rubocop'
  gem 'spring'
  gem 'web-console'
end
